#!/usr/bin/env python3
"""Regenerate corpus/BOOKS.md from the scribe binary.

corpus/BOOKS.md is the desk's authority on which book names exist and
what each one may be called. It is generated, never hand-edited, so that
it can never drift from the corpus it claims to describe.

    ./scripts/generate-books-md.py                 # uses ./target/release/scribe
    SCRIBE_BIN=~/.local/bin/scribe ./scripts/generate-books-md.py
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "corpus" / "BOOKS.md"


def find_scribe() -> str:
    override = os.environ.get("SCRIBE_BIN")
    if override:
        return override
    release = REPO_ROOT / "target" / "release" / "scribe"
    if release.is_file() and os.access(release, os.X_OK):
        return str(release)
    on_path = shutil.which("scribe")
    if on_path:
        return on_path
    sys.exit(
        "no scribe binary found: build one with `cargo build --release`, "
        "or point SCRIBE_BIN at an existing binary"
    )


def load_books(scribe: str) -> list[dict]:
    result = subprocess.run(
        [scribe, "books", "--json"], capture_output=True, text=True, check=True
    )
    return json.loads(result.stdout)["books"]


def split_sections(books: list[dict]) -> list[tuple[str, list[dict]]]:
    """Apocrypha books are exactly the books carrying a Greek coverage
    entry; the Old Testament precedes them and the New Testament follows."""
    apocrypha = [i for i, b in enumerate(books) if b.get("greek_coverage")]
    if not apocrypha:
        sys.exit("scribe books --json reported no Apocrypha coverage; cannot section")
    first, last = apocrypha[0], apocrypha[-1]
    return [
        ("Old Testament", books[:first]),
        ("Apocrypha", books[first : last + 1]),
        ("New Testament", books[last + 1 :]),
    ]


def chapter_span(book: dict) -> str:
    """Most books run 1..n. A few (Rest of Esther) begin partway through,
    and the column has to say so rather than imply chapters that are not
    there."""
    numbers = sorted(c["chapter"] for c in book["chapters"])
    if not numbers:
        return "none"
    first, last = numbers[0], numbers[-1]
    return str(last) if first == 1 else f"{first}\u2013{last}"


def render(books: list[dict], scribe_version: str) -> str:
    lines = [
        "# Books in the corpus",
        "",
        "The exact book names the corpus answers to, and every alias each one",
        "accepts. Check this file before searching — especially in the",
        "Apocrypha, where the printed name a commentary uses and the name this",
        "corpus carries are often not the same word.",
        "",
        "Names are case-insensitive and whitespace-tolerant; a near miss gets a",
        '"did you mean" suggestion rather than a silent wrong answer.',
        "",
        "Generated by `./scripts/generate-books-md.py` from "
        f"`{scribe_version}`. Do not hand-edit.",
        "",
    ]
    for section, section_books in split_sections(books):
        lines.append(f"## {section}")
        lines.append("")
        if section == "Apocrypha":
            lines.append("| Book | Chapters | Aliases | Greek witness |")
            lines.append("|---|---|---|---|")
        else:
            lines.append("| Book | Chapters | Aliases |")
            lines.append("|---|---|---|")
        for book in section_books:
            aliases = ", ".join(f"`{a}`" for a in book["aliases"])
            row = f"| {book['book']} | {chapter_span(book)} | {aliases} |"
            if section == "Apocrypha":
                greek = book.get("greek_coverage") or {}
                row += f" {greek.get('status', 'none')} |"
            lines.append(row)
        lines.append("")
    total = len(books)
    lines.append(f"{total} books.")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    scribe = find_scribe()
    version = subprocess.run(
        [scribe, "--version"], capture_output=True, text=True, check=True
    ).stdout.strip()
    books = load_books(scribe)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(books, version), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(books)} books)")


if __name__ == "__main__":
    main()
